[[redirects]]
  from = "/audit/*"
  to = "/audit/index.html"
  status = 200

[[redirects]]
  from = "/audit"
  to = "/audit/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
