name = "proplum-network"
pages_build_output_dir = "."
compatibility_date = "2026-09-12"
compatibility_flags = ["nodejs_compat"]

# D1 Database Binding
[[d1_databases]]
binding = "PROPLUM_D1"
database_name = "proplum-d1"
database_id = "e91af0ea-9462-47c3-b99d-1e2faffb0e37"

# R2 Bucket Binding
[[r2_buckets]]
binding = "PROPLUM_R2"
bucket_name = "proplum-cache"

[vars]
ENVIRONMENT = "production"
TELNYX_FROM_NUMBER = "+18134913590"
